"""Shared pytest fixtures for the recommender filter suite.

Two fixtures are exposed:

* ``synthetic_df`` — a 20-row, hand-built DataFrame with the exact column
  schema the filters expect. Used by the per-axis unit tests so they don't
  depend on the catalogue CSV being checked in.
* ``real_df``      — the actual ``cleaned_laptops_updated.csv`` catalogue
  (896 rows in W21). Used by the dispatcher snapshot test. Skipped via
  ``pytest.skip`` if the file is missing, so the suite stays green on a
  shallow checkout.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOGUE_CSV = REPO_ROOT / "cleaned_laptops_updated.csv"


@pytest.fixture(scope="session")
def synthetic_df() -> pd.DataFrame:
    """20-row DataFrame covering every axis the filters touch.

    Designed so the per-axis tests can assert exact row counts without
    re-implementing the filter logic. The layout is deliberately uneven —
    e.g. only one Apple row, two touchscreen rows — so a buggy filter
    (`all True` / `all False`) flips an assertion.
    """
    rows = [
        # brand,        os,          price,  ram, ssd, hdd, display, weight,        warranty, Studying, Programming, Gaming, Multimedia, Medium, Advanced, Touchscreen
        (
            "HP",
            "Windows",
            35000,
            4,
            128,
            0,
            14.0,
            "Casual",
            1,
            True,
            False,
            False,
            True,
            False,
            False,
            False,
        ),
        (
            "HP",
            "Windows",
            42000,
            8,
            256,
            0,
            15.6,
            "Casual",
            1,
            True,
            True,
            False,
            True,
            True,
            False,
            False,
        ),
        (
            "HP",
            "Windows",
            58000,
            8,
            512,
            0,
            14.0,
            "ThinNlight",
            2,
            False,
            True,
            False,
            True,
            True,
            False,
            False,
        ),
        (
            "Dell",
            "Windows",
            65000,
            16,
            512,
            0,
            15.6,
            "Casual",
            1,
            False,
            True,
            False,
            False,
            True,
            False,
            False,
        ),
        (
            "Dell",
            "Windows",
            78000,
            16,
            512,
            0,
            13.3,
            "ThinNlight",
            2,
            False,
            True,
            True,
            False,
            True,
            True,
            True,
        ),
        (
            "Dell",
            "Linux",
            39000,
            8,
            256,
            0,
            14.0,
            "Casual",
            1,
            True,
            True,
            False,
            False,
            True,
            False,
            False,
        ),
        (
            "Lenovo",
            "Windows",
            48000,
            8,
            256,
            500,
            15.6,
            "Casual",
            1,
            True,
            False,
            False,
            True,
            True,
            False,
            False,
        ),
        (
            "Lenovo",
            "Windows",
            88000,
            16,
            1024,
            0,
            15.6,
            "Gaming",
            2,
            False,
            False,
            True,
            False,
            False,
            True,
            False,
        ),
        (
            "Lenovo",
            "Windows",
            120000,
            32,
            1024,
            0,
            15.6,
            "Gaming",
            2,
            False,
            True,
            True,
            False,
            False,
            True,
            False,
        ),
        (
            "ASUS",
            "Windows",
            72000,
            16,
            512,
            0,
            14.0,
            "ThinNlight",
            1,
            False,
            True,
            True,
            False,
            True,
            False,
            False,
        ),
        (
            "ASUS",
            "Windows",
            95000,
            16,
            1024,
            0,
            15.6,
            "Gaming",
            2,
            False,
            True,
            True,
            False,
            False,
            True,
            False,
        ),
        (
            "ASUS",
            "DOS",
            33000,
            4,
            128,
            0,
            14.0,
            "Casual",
            1,
            True,
            False,
            False,
            True,
            False,
            False,
            False,
        ),
        (
            "Acer",
            "Windows",
            54000,
            8,
            512,
            0,
            14.0,
            "Casual",
            1,
            True,
            True,
            False,
            True,
            True,
            False,
            False,
        ),
        (
            "Acer",
            "Windows",
            29000,
            4,
            0,
            500,
            15.6,
            "Casual",
            1,
            True,
            False,
            False,
            True,
            False,
            False,
            False,
        ),
        (
            "Apple",
            "macOS",
            115000,
            8,
            256,
            0,
            13.3,
            "ThinNlight",
            1,
            False,
            True,
            False,
            True,
            False,
            True,
            False,
        ),
        (
            "MSI",
            "Windows",
            135000,
            16,
            1024,
            0,
            15.6,
            "Gaming",
            2,
            False,
            True,
            True,
            False,
            False,
            True,
            False,
        ),
        (
            "MSI",
            "Windows",
            89000,
            16,
            512,
            0,
            15.6,
            "Gaming",
            2,
            False,
            False,
            True,
            False,
            False,
            True,
            False,
        ),
        (
            "Samsung",
            "Windows",
            62000,
            8,
            256,
            0,
            13.3,
            "ThinNlight",
            1,
            False,
            True,
            False,
            True,
            True,
            False,
            True,
        ),
        (
            "LG",
            "Windows",
            71000,
            8,
            512,
            0,
            14.0,
            "ThinNlight",
            2,
            False,
            True,
            False,
            False,
            True,
            False,
            False,
        ),
        (
            "Avita",
            "Windows",
            26000,
            4,
            128,
            0,
            14.0,
            "Casual",
            1,
            True,
            False,
            False,
            True,
            False,
            False,
            False,
        ),
    ]
    columns = [
        "brand",
        "os",
        "latest_price",
        "ram_gb",
        "ssd",
        "hdd",
        "display_size",
        "weight",
        "warranty",
        "Studying",
        "Programming",
        "Gaming",
        "Multimedia",
        "Medium",
        "Advanced",
        "Touchscreen",
    ]
    return pd.DataFrame(rows, columns=columns)


@pytest.fixture(scope="session")
def real_df() -> pd.DataFrame:
    """The actual catalogue CSV the Streamlit app loads at runtime.

    Skipped (not failed) if the file is absent so a tarball-style checkout
    without the data file still passes the unit tests.
    """
    if not CATALOGUE_CSV.exists():
        pytest.skip(f"catalogue CSV missing at {CATALOGUE_CSV}")
    return pd.read_csv(CATALOGUE_CSV)
